server:
  port: 8086
  servlet:
    contextPath: /userissuer/v1

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: kunal
    password: kunal
    url: jdbc:mysql://localhost:3306/user_db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

my-env: default

---
spring:
  profiles: local
  flyway:
    url: jdbc:mysql://localhost:3306/user_db
    user: kunal
    password: kunal
    schemas: user_db
    locations: classpath:db/migration

my-env: local

---
spring:
  profiles: developement

my-env: development

---
spring:
  profiles: dev

my-env: dev

---
spring:
  profiles: cloud

my-env: ${MY_ENV}
