server:
  port: 8086
  servlet:
    contextPath: /userissuer/v1

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: kunal
    password: kunal
    url: jdbc:mysql://localhost:3306/user_db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect